[project]
name = "sample-analyzer"
version = "0.1.0"
description = "Interactive Streamlit app for analyzing unsuccessful eval samples"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.28.0",
    "pandas>=2.0.0"
]

[project.scripts]
sample-analyzer = "sample_analyzer:main"